services:
  app:
    container_name: app
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    # network_mode: "host"
    ports:
      - ${APP_PORT}:${APP_PORT}

  database:
    container_name: database
    image: postgres:15
    volumes:
      # - ./initdb.sql:/docker-entrypoint-initdb.d
      - database:/usr/src/data/database
    command: "python database/models.py"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_INTERNAL_PORT}:${DB_PORT}
volumes:
  database: